DELETE FROM game_features;

INSERT INTO game_features (game_id, story_mode, open_world, police, tuning, play_as_police, multiplayer) VALUES
(1, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
(2, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
(3, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
(4, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
(5, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
(6, FALSE, FALSE, TRUE, TRUE, FALSE, TRUE),
(7, TRUE, FALSE, FALSE, TRUE, FALSE, TRUE),
(8, TRUE, FALSE, TRUE, TRUE, FALSE, TRUE),
(9, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE),
(10, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE),
(11, TRUE, FALSE, FALSE, TRUE, FALSE, TRUE),
(12, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE),
(13, TRUE, FALSE, TRUE, TRUE, FALSE, TRUE),
(14, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE),
(15, TRUE, FALSE, TRUE, TRUE, FALSE, TRUE),
(16, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE),
(17, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE),
(18, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE),
(19, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE),
(20, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE),
(21, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE);